#!/usr/bin/env python3
import csv

videos = [
    {
        'id': '1',
        'type': 'Educational',
        'title': 'La Verdad sobre la Sal',
        'hook': '¿Por qué nos dijeron que la sal es mala pero los atletas profesionales la consumen a montones?',
        'mainPoints': 'Pierdes 500-1000mg de sodio por litro de sudor|Durante ejercicio intenso pierdes hasta 2L por hora|La mayoría de bebidas deportivas solo tienen 20-50mg',
        'conclusion': 'BILAN tiene 1000mg de sodio por porción - lo que tu cuerpo científicamente necesita',
        'myth': '',
        'truth': '',
        'explanation': '',
        'tip': '',
        'reason': '',
        'duration': '60',
        'scenes': '',
        'trendingFormat': '',
        'cta': 'Dime en los comentarios si ya sabías esto',
        'brandColor': '#0066CC'
    },
    {
        'id': '2',
        'type': 'QuickTip',
        'title': '3 Señales de Deshidratación',
        'hook': 'El 75% de los mexicanos están deshidratados ahora mismo y ni siquiera lo saben',
        'mainPoints': '',
        'conclusion': '',
        'myth': '',
        'truth': '',
        'explanation': '',
        'tip': 'Orina amarillo oscuro significa modo emergencia|Cansancio que no se va ni con café|Antojos locos de sal o azúcar',
        'reason': 'Tu cuerpo confunde falta de electrolitos con hambre',
        'duration': '30',
        'scenes': '',
        'trendingFormat': '',
        'cta': 'Guarda este video y chécate',
        'brandColor': '#0066CC'
    },
    {
        'id': '3',
        'type': 'Mythbusting',
        'title': 'El Mito de los 8 Vasos',
        'hook': 'Los 8 vasos de agua al día son un mito y te voy a decir por qué',
        'mainPoints': '',
        'conclusion': '',
        'myth': 'Este consejo viene de un estudio de los años 40 que fue malinterpretado',
        'truth': 'Tu necesidad de agua depende de tu peso actividad y clima',
        'explanation': 'Un oficinista de 60kg en CDMX no necesita lo mismo que un albañil de 90kg en Monterrey con 40 grados',
        'tip': '',
        'reason': '',
        'duration': '45',
        'scenes': '',
        'trendingFormat': '',
        'cta': 'Dime cuánta agua tomas tú al día',
        'brandColor': '#0066CC'
    },
    {
        'id': '4',
        'type': 'Mythbusting',
        'title': 'Trampa de Bebidas Deportivas',
        'hook': 'Me gasté cientos de pesos en bebidas deportivas antes de darme cuenta de que me estaban viendo la cara',
        'mainPoints': '',
        'conclusion': '',
        'myth': 'Las bebidas deportivas del súper tienen solo 20-50mg de sodio',
        'truth': 'Necesitas 500-1000mg por litro de sudor',
        'explanation': 'Aparte tienen 30g de azúcar - casi como un refresco. BILAN tiene 1000mg sodio y 0g azúcar',
        'tip': '',
        'reason': '',
        'duration': '45',
        'scenes': '',
        'trendingFormat': '',
        'cta': 'Lee la etiqueta la próxima vez',
        'brandColor': '#0066CC'
    },
    {
        'id': '5',
        'type': 'Trending',
        'title': 'Cómo Me Curé de los Calambres',
        'hook': 'Durante 3 años no pude terminar un partido de futbol completo por los calambres. Hasta que descubrí esto',
        'mainPoints': '',
        'conclusion': '',
        'myth': '',
        'truth': '',
        'explanation': '',
        'tip': '',
        'reason': '',
        'duration': '60',
        'scenes': 'Calambres cada partido minuto 60-70|Probé plátanos agua pastillas - nada funcionó|Descubrí que necesitaba SODIO no solo potasio|Ahora juego 90 minutos completos sin calambres',
        'trendingFormat': 'transformation',
        'cta': 'Dime dónde te dan calambres a ti',
        'brandColor': '#0066CC'
    },
    {
        'id': '6',
        'type': 'Trending',
        'title': 'Transformación en el Gym',
        'hook': 'Aumenté 15% mi rendimiento en el gym sin cambiar mi rutina ni mi dieta. Solo cambié esto',
        'mainPoints': '',
        'conclusion': '',
        'myth': '',
        'truth': '',
        'explanation': '',
        'tip': '',
        'reason': '',
        'duration': '60',
        'scenes': 'Antes: Cansancio dolores de cabeza DOMS de 3-4 días|El cambio: Agregué electrolitos a mi hidratación|Después: Más energía pesos subieron 10-15%|Solo agregué BILAN',
        'trendingFormat': 'transformation',
        'cta': 'Comenta tu ejercicio principal',
        'brandColor': '#0066CC'
    },
    {
        'id': '7',
        'type': 'QuickTip',
        'title': 'Tip de Hidratación 15s',
        'hook': 'Este truco de hidratación te puede salvar en tu próximo entrenamiento',
        'mainPoints': '',
        'conclusion': '',
        'myth': '',
        'truth': '',
        'explanation': '',
        'tip': 'Pellizca tu piel en el dorso de la mano',
        'reason': 'Si vuelve lento estás deshidratado - si vuelve rápido estás bien',
        'duration': '15',
        'scenes': '',
        'trendingFormat': '',
        'cta': 'Guarda esto y usa BILAN',
        'brandColor': '#0066CC'
    },
    {
        'id': '8',
        'type': 'QuickTip',
        'title': 'Secreto de los Atletas',
        'hook': 'Los atletas profesionales no toman agua durante entrenamientos. Toman esto',
        'mainPoints': '',
        'conclusion': '',
        'myth': '',
        'truth': '',
        'explanation': '',
        'tip': 'Cuando sudas intensamente el agua sola no te rehidrata',
        'reason': 'Los atletas de élite reponen electrolitos - 1000mg de sodio por hora. BILAN tiene esa fórmula',
        'duration': '30',
        'scenes': '',
        'trendingFormat': '',
        'cta': 'Sígueme para más secretos',
        'brandColor': '#0066CC'
    },
    {
        'id': '9',
        'type': 'Trending',
        'title': 'POV Olvidas Electrolitos',
        'hook': 'POV: Olvidaste tus electrolitos y ya vas en el minuto 45 de cardio',
        'mainPoints': '',
        'conclusion': '',
        'myth': '',
        'truth': '',
        'explanation': '',
        'tip': '',
        'reason': '',
        'duration': '30',
        'scenes': 'Minuto 15: Todo bien estoy bien|Minuto 30: Por qué me siento mareado|Minuto 45: Chale me está dando calambre|Minuto 60: Por qué me odia mi cuerpo',
        'trendingFormat': 'pov',
        'cta': 'No seas payaso trae tu BILAN',
        'brandColor': '#0066CC'
    },
    {
        'id': '10',
        'type': 'Trending',
        'title': 'Tutorial Hidratación Perfecta',
        'hook': 'Tutorial: Cómo hidratarte como los atletas profesionales en 3 pasos',
        'mainPoints': '',
        'conclusion': '',
        'myth': '',
        'truth': '',
        'explanation': '',
        'tip': '',
        'reason': '',
        'duration': '45',
        'scenes': 'PASO 1: Pre-entrenamiento - 500ml con BILAN 2h antes|PASO 2: Durante - 250ml cada 15-20min|PASO 3: Post - 500-750ml en la siguiente hora',
        'trendingFormat': 'tutorial',
        'cta': 'Guarda este tutorial',
        'brandColor': '#0066CC'
    }
]

fieldnames = ['id', 'type', 'title', 'hook', 'mainPoints', 'conclusion', 'myth', 'truth', 'explanation', 'tip', 'reason', 'duration', 'scenes', 'trendingFormat', 'cta', 'brandColor']

with open('src/data/videos-mx-2026-01-23.csv', 'w', newline='', encoding='utf-8') as csvfile:
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    for video in videos:
        writer.writerow(video)

print("CSV file generated successfully!")
print(f"Created {len(videos)} video entries")
